FROM node:20-alpine

WORKDIR /app

# Étape 1 : installation des deps
COPY package.json package-lock.json ./
RUN npm install

# Étape 2 : copie du reste
COPY . .

# Variables utiles
ENV NODE_ENV=development
ENV SKIP_ENV_VALIDATION=1

EXPOSE 3000

CMD ["npm", "run", "dev:init"]
